modLoader = "javafml"
loaderVersion = "[34,)"
issueTrackerURL = "https://github.com/cofh/feedback"
license = "CoFH - Don't Be A Jerk (Learn, Don't Steal)"

[[mods]]
modId = "thermal_cultivation"
version = "${file.jarVersion}"
displayName = "Thermal Cultivation"
displayURL = "https://teamcofh.com/"
logoFile = "thermal_cultivation.png"
credits = "Team CoFH"
authors = "King Lemming"
description = '''
Thermal gets agrarian!

Contains the "farm" of the Thermal Series - various crops, foods, and associated gadgetry.
'''
[[dependencies.thermal_cultivation]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_cultivation]]
modId = "forge"
mandatory = true
versionRange = "[36.2.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_cultivation]]
modId = "cofh_core"
mandatory = true
versionRange = "[1.4,1.5]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_cultivation]]
modId = "thermal"
mandatory = true
versionRange = "[1.4,1.5]"
ordering = "AFTER"
side = "BOTH"