modLoader = "javafml"
loaderVersion = "[${forge_major_version},)"
issueTrackerURL = "https://github.com/cofh/feedback"
license = "CoFH - Don't Be A Jerk (Learn, Don't Steal)"

[[mods]]
modId = "thermal_cultivation"
version = "${file.jarVersion}"
displayName = "Thermal Cultivation"
updateJSONURL = "https://raw.github.com/cofh/version/main/thermal/update_cultivation.json"
displayURL = "https://teamcofh.com/"
logoFile = "thermal_cultivation.png"
itemIcon = "thermal:flax"
credits = "Team CoFH"
authors = "King Lemming"
description = '''
Thermal gets agrarian!

Contains the "farm" of the Thermal Series - various crops, foods, and associated gadgetry.
'''
[[dependencies.thermal_cultivation]]
modId = "minecraft"
mandatory = true
versionRange = "1.20.1"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_cultivation]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_cultivation]]
modId = "cofh_core"
mandatory = true
versionRange = "${cofh_core_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_cultivation]]
modId = "thermal"
mandatory = true
versionRange = "${thermal_core_version_range}"
ordering = "AFTER"
side = "BOTH"