modLoader = "javafml"
loaderVersion = "[34,)"
issueTrackerURL = "https://github.com/cofh/feedback"
license = "CoFH - Don't Be A Jerk (Learn, Don't Steal)"

[[mods]]
modId = "thermal_cultivation"
version = "${file.jarVersion}"
displayName = "Thermal Cultivation"
updateJSONURL = "https://raw.github.com/cofh/version/master/thermal/update_cultivation.json"
displayURL = "https://teamcofh.com/"
logoFile = "thermal_cultivation.png"
itemIcon = "thermal:flax"
credits = "Team CoFH"
authors = "King Lemming"
description = '''
Thermal gets agrarian!

Contains the "farm" of the Thermal Series - various crops, foods, and associated gadgetry.
'''
[[dependencies.thermal_cultivation]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_cultivation]]
modId = "forge"
mandatory = true
versionRange = "[40.1.76,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_cultivation]]
modId = "cofh_core"
mandatory = true
versionRange = "[9.1,9.2]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_cultivation]]
modId = "thermal"
mandatory = true
versionRange = "[9.1,9.2]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_cultivation]]
modId = "thermal_foundation"
mandatory = true
versionRange = "[9.1,9.2]"
ordering = "AFTER"
side = "BOTH"